kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: helsemelding-kafka-manager
  namespace: helsemelding
  labels:
    team: helsemelding
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2.2021.05.31_08.41-622e72c02ee1
  port: 8080
  webproxy: true
  ingresses:
    - https://helsemelding-kafka-manager.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: b1d4f279-fbc2-4fe7-8c77-4724edc23440 # Required for authorization
  kafka: # Optional. Required for Aiven
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "helsemelding.dialog.out.xml",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "helsemelding.dialog.in.xml",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
